tidysic/tidysic

- src/__argparse__.py
- src/tidysic.py
Close #1 
This is still a very basic argument parsing (only one subcommand was created). But it will serve as a base and example for future additions.
> Add argparse to project

- README.md
- requirements.txt
- src/__argparse__.py
- src/tidysic.py
Close #6 
Two modules are added:
* [flake8](https://github.com/PyCQA/flake8) for lint
* [autopep8](https://github.com/hhatto/autopep8#more-advanced-usage) for automatic code fix
Two commands are added to the main script:
* lint (use flake8 to lint)
* lintfix (use autopep8 to try and fix the code)
Those commands are run recursively inside the *src* directory.
> Add python linter

- README.md
- src/tidysic.py
- test/__init__.py
- test/test_example.py
> Setup testing

- requirements.txt
- src/__argparse__.py
- src/__os_utils__.py
- src/tidysic.py
- src/tidysic_gui.py
Added PyQt requirements, and a starter GUI script. Close #2 
Refactored most of the existing code, mostly in order to call the methods from the GUI. Awaiting discussions on some choices I've made, since they can be quite substantial at times.
> PyQt setup

- requirements.txt
Did you forget to run *pip freeze* @g-wizzy  hihi
> Add rich module to requirements.txt

- src/__argparse__.py
- src/__os_utils__.py
- src/tidysic.py
> Ignore if no artist optional album

- src/__argparse__.py
- src/__logger__.py
- src/__os_utils__.py
- src/tidysic.py
Cosmetic improvements to the _dry run_ capabilities of tidysic.
> Better log

- tidysic/__init__.py
- tidysic/algorithms.py
- tidysic/gui/tidysic_gui.py
- tidysic/logger.py
- tidysic/os_utils.py
> Clt quickfixes

- tidysic/__init__.py
- tidysic/algorithms.py
> cleanup function

- tidysic/os_utils.py
> Verbosification

- tidysic/audio_file.py
> Ultra quick fix

- test/test_algorithm.py
- tidysic/__init__.py
- tidysic/audio_file.py
- tidysic/gui/main_window.py
- tidysic/gui/widgets/files_visualizer.py
- tidysic/gui/widgets/tags_editor.py
- tidysic/main.py
- tidysic/tidysic.py
Not much to see here, Renamed `algorithms.py` to `tidysic.py`, and hid the utils so that the base package is friendlier.
> Streamlining

- .github/workflows/python-app.yml
- pyproject.toml
- tidysic/logger.py
- tidysic/os_utils.py
> Fix verbose logs being tagged as dry run

- README.md
- cli_tool
- pyproject.toml
This leverages the power of poetry to be able to call the `tidysic` command within a `poetry shell`.
> Byebye cli_tools 👋, meet 'tidysic' command

- test/test_algorithm.py
- tidysic/__init__.py
- tidysic/audio_file.py
- tidysic/formatted_string.py
- tidysic/main.py
- tidysic/ordering.py
- tidysic/tidysic.py
Close #32 
Also creates classes for ordering (sequence of tags by which to create folders (e.g. artist, album, track), and for formatted strings (used to customize folder and file names after moving).
> Wrap in class

- tidysic/tidysic.py
Some dumb mistake caused intermittent dropping of clutter files.
> Fix clutter assignment

- tidysic/audio_file.py
- tidysic/formatted_string.py
- tidysic/logger.py
- tidysic/ordering.py
- tidysic/tidysic.py
This PR solves #82.
I took the liberty to `sort import` on all the files too, since this PR is about cleaning imports anyway.
> no more import inside functions

- .github/workflows/python-app.yml
Some improvements to the GitHub Action:
- add branch v2 to the GH Actions
- remove the poetry action dependency
- cache virtualenv
- run parallel jobs
> GH Actions enhancements

- .github/workflows/python-app.yml
- .gitignore
- .vscode/settings.json.default
Port this feature from `main` to `v2`
> Vscode settings

- .github/workflows/python-app.yml
- tidysic/file/taggable.py
- tidysic/file/tagged_file.py
- tidysic/main.py
- tidysic/organizer.py
- tidysic/parser/tree.py
- tidysic/settings/formatted_string.py
- tidysic/settings/parser.py
Still relies on regex, but hopefully more in a more readable and maintainable manner.
Now parses the substitutions to make on initialization, instead of during string building.
> Refactor formatted_string.py

- poetry.lock
- pyproject.toml
- tidysic/main.py
- tidysic/settings/structure.py
- tidysic/tidysic.py
Fix wrong typing, move some code belonging to `structure` out of `tidysic`
⚠️ BTW, running the CLI with the default structure fails! (also in `main`). You may want to add a test for making sure the trivial case without custom config works.
> clean sructure.py code

- .github/workflows/python-app.yml
> Fix pipeline

- tidysic/main.py
- tidysic/organizer.py
- tidysic/tidysic.py
> Restore dry run

- tidysic/parser.py
- tidysic/tidysic.py
> Clean up after tidying.
